const fifaData = [
  {
    player: "Ronaldo",
    year: 2018,
    goals: 40,
    assists: 10,
    penalties: 5,
    headers: 12,
    fieldGoals: 28,
    speed: 85,
    accuracy: 90,
    strength: 88,
  },
  {
    player: "Messi",
    year: 2018,
    goals: 45,
    assists: 15,
    penalties: 7,
    headers: 5,
    fieldGoals: 33,
    speed: 88,
    accuracy: 92,
    strength: 75,
  },
  {
    player: "Ronaldo",
    year: 2019,
    goals: 35,
    assists: 8,
    penalties: 6,
    headers: 10,
    fieldGoals: 25,
    speed: 84,
    accuracy: 88,
    strength: 85,
  },
  {
    player: "Messi",
    year: 2019,
    goals: 50,
    assists: 20,
    penalties: 8,
    headers: 6,
    fieldGoals: 36,
    speed: 87,
    accuracy: 91,
    strength: 76,
  },
  {
    player: "Ronaldo",
    year: 2020,
    goals: 30,
    assists: 12,
    penalties: 7,
    headers: 8,
    fieldGoals: 22,
    speed: 86,
    accuracy: 89,
    strength: 87,
  },
  {
    player: "Messi",
    year: 2020,
    goals: 40,
    assists: 18,
    penalties: 6,
    headers: 4,
    fieldGoals: 34,
    speed: 89,
    accuracy: 93,
    strength: 78,
  },
  {
    player: "Ronaldo",
    year: 2021,
    goals: 35,
    assists: 10,
    penalties: 6,
    headers: 10,
    fieldGoals: 25,
    speed: 85,
    accuracy: 88,
    strength: 86,
  },
  {
    player: "Messi",
    year: 2021,
    goals: 48,
    assists: 22,
    penalties: 7,
    headers: 5,
    fieldGoals: 43,
    speed: 88,
    accuracy: 92,
    strength: 77,
  },
  {
    player: "Ronaldo",
    year: 2022,
    goals: 28,
    assists: 15,
    penalties: 5,
    headers: 7,
    fieldGoals: 21,
    speed: 87,
    accuracy: 90,
    strength: 85,
  },
  {
    player: "Messi",
    year: 2022,
    goals: 42,
    assists: 20,
    penalties: 8,
    headers: 6,
    fieldGoals: 36,
    speed: 89,
    accuracy: 94,
    strength: 80,
  },
  {
    player: "Kylian Mbappé",
    year: 2018,
    goals: 30,
    assists: 12,
    penalties: 5,
    headers: 3,
    fieldGoals: 22,
    speed: 92,
    accuracy: 85,
    strength: 78,
  },
  {
    player: "Kylian Mbappé",
    year: 2019,
    goals: 39,
    assists: 17,
    penalties: 6,
    headers: 4,
    fieldGoals: 35,
    speed: 94,
    accuracy: 88,
    strength: 80,
  },
  {
    player: "Kylian Mbappé",
    year: 2020,
    goals: 27,
    assists: 10,
    penalties: 4,
    headers: 5,
    fieldGoals: 22,
    speed: 93,
    accuracy: 87,
    strength: 76,
  },
  {
    player: "Kylian Mbappé",
    year: 2021,
    goals: 33,
    assists: 15,
    penalties: 7,
    headers: 6,
    fieldGoals: 27,
    speed: 94,
    accuracy: 89,
    strength: 79,
  },
  {
    player: "Kylian Mbappé",
    year: 2022,
    goals: 29,
    assists: 14,
    penalties: 5,
    headers: 3,
    fieldGoals: 24,
    speed: 95,
    accuracy: 90,
    strength: 77,
  },
  {
    player: "Neymar",
    year: 2018,
    goals: 25,
    assists: 18,
    penalties: 3,
    headers: 2,
    fieldGoals: 20,
    speed: 91,
    accuracy: 86,
    strength: 75,
  },
  {
    player: "Neymar",
    year: 2019,
    goals: 29,
    assists: 20,
    penalties: 4,
    headers: 3,
    fieldGoals: 26,
    speed: 90,
    accuracy: 87,
    strength: 76,
  },
  {
    player: "Neymar",
    year: 2020,
    goals: 22,
    assists: 12,
    penalties: 2,
    headers: 1,
    fieldGoals: 19,
    speed: 91,
    accuracy: 88,
    strength: 74,
  },
  {
    player: "Neymar",
    year: 2021,
    goals: 26,
    assists: 15,
    penalties: 3,
    headers: 2,
    fieldGoals: 21,
    speed: 92,
    accuracy: 89,
    strength: 76,
  },
  {
    player: "Neymar",
    year: 2022,
    goals: 20,
    assists: 10,
    penalties: 1,
    headers: 2,
    fieldGoals: 17,
    speed: 93,
    accuracy: 90,
    strength: 77,
  },
  {
    player: "Robert Lewandowski",
    year: 2018,
    goals: 35,
    assists: 5,
    penalties: 8,
    headers: 15,
    fieldGoals: 20,
    speed: 85,
    accuracy: 88,
    strength: 85,
  },
  {
    player: "Robert Lewandowski",
    year: 2019,
    goals: 45,
    assists: 7,
    penalties: 9,
    headers: 20,
    fieldGoals: 25,
    speed: 86,
    accuracy: 89,
    strength: 86,
  },
  {
    player: "Robert Lewandowski",
    year: 2020,
    goals: 40,
    assists: 8,
    penalties: 7,
    headers: 18,
    fieldGoals: 22,
    speed: 87,
    accuracy: 90,
    strength: 87,
  },
  {
    player: "Robert Lewandowski",
    year: 2021,
    goals: 50,
    assists: 10,
    penalties: 11,
    headers: 22,
    fieldGoals: 28,
    speed: 88,
    accuracy: 91,
    strength: 88,
  },
  {
    player: "Robert Lewandowski",
    year: 2022,
    goals: 45,
    assists: 9,
    penalties: 10,
    headers: 21,
    fieldGoals: 24,
    speed: 89,
    accuracy: 92,
    strength: 89,
  },
];

export default fifaData;
